# Generated by Django 5.1.15 on 2026-08-12 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('contacto', models.CharField(blank=True, max_length=150, verbose_name='contacto')),
                ('contrata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='accounts.contrata', verbose_name='contrata')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EsquemaColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('ambito', models.CharField(choices=[('DIN_VDE0888', 'DIN VDE 0888'), ('TIA_568', 'TIA-568'), ('PRIVADO', 'Privado')], max_length=20, verbose_name='ámbito')),
                ('colores', models.JSONField(help_text='Array ordenado de 12 colores (tubos/fibras 1-12).', verbose_name='colores')),
                ('contrata', models.ForeignKey(blank=True, help_text='Nulo = esquema global del sistema.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esquemas_color', to='accounts.contrata', verbose_name='contrata')),
            ],
            options={
                'verbose_name': 'esquema de color',
                'verbose_name_plural': 'esquemas de color',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilOperadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('umbrales', models.JSONField(default=dict, help_text='Formato: {"SM": {"ok": x, "warn": y}, "MM": {...}}', verbose_name='umbrales (dB)')),
                ('potencia_min_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='potencia mínima (dBm)')),
                ('potencia_max_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='potencia máxima (dBm)')),
                ('arquitectura', models.CharField(choices=[('GPON_CENTRALIZADA', 'GPON centralizada'), ('GPON_CASCADA', 'GPON en cascada'), ('GPON_DISTRIBUIDA', 'GPON distribuida'), ('P2P_SIN_SPLITTER', 'P2P sin splitter'), ('MIXTA', 'Mixta')], default='GPON_CASCADA', max_length=20, verbose_name='arquitectura por defecto')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='core.cliente', verbose_name='cliente')),
                ('esquema_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='core.esquemacolor', verbose_name='esquema de color')),
            ],
            options={
                'verbose_name': 'perfil de operadora',
                'verbose_name_plural': 'perfiles de operadora',
            },
        ),
        migrations.CreateModel(
            name='TarifaUO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='código')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('vigente', models.BooleanField(default=True, verbose_name='vigente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='core.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'tarifa de unidades de obra',
                'verbose_name_plural': 'tarifas de unidades de obra',
            },
        ),
        migrations.CreateModel(
            name='TarifaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej.: FUS-EMPALME, MONT-CTO-16, M-TENDIDO.', max_length=50, verbose_name='código')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio (€)')),
                ('unidad', models.CharField(help_text='Ej.: ud, m, fusión.', max_length=20, verbose_name='unidad')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.tarifauo', verbose_name='tarifa')),
            ],
            options={
                'verbose_name': 'ítem de tarifa',
                'verbose_name_plural': 'ítems de tarifa',
            },
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('contrata', 'nombre'), name='uniq_cliente_nombre_contrata'),
        ),
        migrations.AddConstraint(
            model_name='tarifauo',
            constraint=models.UniqueConstraint(fields=('cliente', 'codigo'), name='uniq_tarifa_codigo_cliente'),
        ),
        migrations.AddConstraint(
            model_name='tarifaitem',
            constraint=models.UniqueConstraint(fields=('tarifa', 'codigo'), name='uniq_item_codigo_tarifa'),
        ),
    ]
