# Generated by Django 5.1.15 on 2026-08-12 17:16

import apps.network.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='código')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
                ('ubicacion', models.CharField(blank=True, help_text='Municipio / zona.', max_length=150, verbose_name='ubicación')),
                ('arquitectura', models.CharField(choices=[('GPON_CENTRALIZADA', 'GPON centralizada'), ('GPON_CASCADA', 'GPON en cascada'), ('GPON_DISTRIBUIDA', 'GPON distribuida'), ('P2P_SIN_SPLITTER', 'P2P sin splitter'), ('MIXTA', 'Mixta')], max_length=20, verbose_name='arquitectura')),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('EN_CURSO', 'En curso'), ('EJECUTADA', 'Ejecutada'), ('MEDIDA', 'Medida'), ('VALIDADA', 'Validada'), ('CERTIFICADA', 'Certificada'), ('FACTURADA', 'Facturada')], default='PLANIFICADA', max_length=20, verbose_name='estado')),
                ('umbrales', models.JSONField(default=apps.network.models.umbrales_defecto, help_text='Formato: {"SM": {"ok": x, "warn": y}, "MM": {...}}', verbose_name='umbrales (dB)')),
                ('potencia_min_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='potencia mínima (dBm)')),
                ('potencia_max_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='potencia máxima (dBm)')),
                ('requiere_otdr', models.BooleanField(default=False, verbose_name='requiere OTDR')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='core.cliente', verbose_name='cliente')),
                ('contrata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='accounts.contrata', verbose_name='contrata')),
                ('perfil_operadora', models.ForeignKey(blank=True, help_text='Si se deja vacío se copian los defaults del perfil del cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras', to='core.perfiloperadora', verbose_name='perfil de operadora')),
            ],
            options={
                'verbose_name': 'obra',
                'verbose_name_plural': 'obras',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ElementoRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMPALME', 'Empalme'), ('CTO', 'CTO (caja terminal óptica)'), ('REGISTRO', 'Registro'), ('ODF', 'ODF'), ('CJA_TERMINAL', 'Caja terminal')], max_length=20, verbose_name='tipo')),
                ('codigo', models.CharField(max_length=50, verbose_name='código')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
                ('ubicacion_tipo', models.CharField(choices=[('ARQUETA', 'Arqueta'), ('AEREO_FACHADA', 'Aéreo en fachada'), ('AEREO_POSTE', 'Aéreo en poste'), ('INTERIOR_ICT', 'Interior (ICT)'), ('CENTRO_ODF', 'Centro / ODF')], max_length=20, verbose_name='tipo de ubicación')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud')),
                ('capacidad_puertos', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacidad de puertos')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='network.obra', verbose_name='obra')),
            ],
            options={
                'verbose_name': 'elemento de red',
                'verbose_name_plural': 'elementos de red',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='código')),
                ('tipo_cable', models.CharField(choices=[('EXTERIOR', 'Exterior'), ('INTERIOR', 'Interior'), ('RISER', 'Riser'), ('ADSS', 'ADSS'), ('DROP', 'Drop'), ('MICRO', 'Micro')], max_length=20, verbose_name='tipo de cable')),
                ('tipo_fibra', models.CharField(choices=[('SM_G652D', 'SM G.652.D'), ('SM_G657A1', 'SM G.657.A1'), ('SM_G657A2', 'SM G.657.A2'), ('MM_OM3', 'MM OM3'), ('MM_OM4', 'MM OM4')], max_length=20, verbose_name='tipo de fibra')),
                ('n_tubos', models.PositiveIntegerField(verbose_name='nº de tubos')),
                ('fibras_por_tubo', models.PositiveIntegerField(verbose_name='fibras por tubo')),
                ('longitud_m', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='longitud (m)')),
                ('elemento_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cables_como_a', to='network.elementored', verbose_name='elemento A')),
                ('elemento_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cables_como_b', to='network.elementored', verbose_name='elemento B')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cables', to='network.obra', verbose_name='obra')),
            ],
            options={
                'verbose_name': 'cable',
                'verbose_name_plural': 'cables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TENDIDO', 'Tendido'), ('FUSION', 'Fusión'), ('MONTAJE_CTO', 'Montaje de CTO'), ('MEDICION', 'Medición'), ('AVERIA', 'Avería')], max_length=20, verbose_name='tipo')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('VALIDADA', 'Validada')], default='ASIGNADA', max_length=20, verbose_name='estado')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='network.obra', verbose_name='obra')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='accounts.trabajador', verbose_name='trabajador')),
            ],
            options={
                'verbose_name': 'orden de trabajo',
                'verbose_name_plural': 'órdenes de trabajo',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PasoTubo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tubo', models.PositiveIntegerField(verbose_name='tubo')),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_tubo', to='network.cable', verbose_name='cable')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_tubo', to='network.elementored', verbose_name='elemento')),
            ],
            options={
                'verbose_name': 'paso de tubo',
                'verbose_name_plural': 'pasos de tubo',
            },
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FIBRA_CABLE', 'Fibra de cable'), ('PUERTO_SPLITTER_IN', 'Entrada de splitter'), ('PUERTO_SPLITTER_OUT', 'Salida de splitter'), ('PIGTAIL', 'Pigtail'), ('RESERVA', 'Reserva')], max_length=20, verbose_name='tipo')),
                ('tubo', models.PositiveIntegerField(blank=True, null=True, verbose_name='tubo')),
                ('fibra', models.PositiveIntegerField(blank=True, null=True, verbose_name='fibra (dentro del tubo)')),
                ('puerto', models.PositiveIntegerField(blank=True, null=True, verbose_name='nº de puerto')),
                ('reservado_para', models.CharField(blank=True, max_length=150, verbose_name='reservado para')),
                ('cable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puertos', to='network.cable', verbose_name='cable')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertos', to='network.elementored', verbose_name='elemento')),
            ],
            options={
                'verbose_name': 'puerto',
                'verbose_name_plural': 'puertos',
            },
        ),
        migrations.CreateModel(
            name='Fusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perdida_db', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='pérdida (dB)')),
                ('bandeja', models.PositiveIntegerField(blank=True, null=True, verbose_name='bandeja')),
                ('posicion', models.PositiveIntegerField(blank=True, null=True, verbose_name='posición en bandeja')),
                ('estado', models.CharField(choices=[('EJECUTADA', 'Ejecutada'), ('MEDIDA', 'Medida'), ('VALIDADA', 'Validada')], default='EJECUTADA', max_length=20, verbose_name='estado')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versión')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusiones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fusiones', to='network.elementored', verbose_name='elemento')),
                ('sustituida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sustituye_a', to='network.fusion', verbose_name='sustituida por')),
                ('puerto_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fusiones_como_a', to='network.puerto', verbose_name='puerto A')),
                ('puerto_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fusiones_como_b', to='network.puerto', verbose_name='puerto B')),
            ],
            options={
                'verbose_name': 'fusión',
                'verbose_name_plural': 'fusiones',
            },
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EJECUTADA', 'Ejecutada'), ('MEDIDA', 'Medida'), ('VALIDADA', 'Validada')], default='EJECUTADA', max_length=20, verbose_name='estado')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versión')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conexiones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('sustituida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sustituye_a', to='network.conexion', verbose_name='sustituida por')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones', to='network.elementored', verbose_name='elemento')),
                ('puerto_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conexiones_como_a', to='network.puerto', verbose_name='puerto A')),
                ('puerto_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conexiones_como_b', to='network.puerto', verbose_name='puerto B')),
            ],
            options={
                'verbose_name': 'conexión',
                'verbose_name_plural': 'conexiones',
            },
        ),
        migrations.CreateModel(
            name='Splitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.CharField(choices=[('1:2', '1:2'), ('1:4', '1:4'), ('1:8', '1:8'), ('1:16', '1:16'), ('1:32', '1:32'), ('1:64', '1:64')], max_length=5, verbose_name='ratio')),
                ('cascada_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splitters_cascada', to='network.splitter', verbose_name='en cascada de')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitters', to='network.elementored', verbose_name='elemento')),
            ],
            options={
                'verbose_name': 'splitter',
                'verbose_name_plural': 'splitters',
            },
        ),
        migrations.AddField(
            model_name='puerto',
            name='splitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puertos', to='network.splitter', verbose_name='splitter'),
        ),
        migrations.AddConstraint(
            model_name='obra',
            constraint=models.UniqueConstraint(fields=('contrata', 'codigo'), name='uniq_obra_codigo_contrata'),
        ),
        migrations.AddConstraint(
            model_name='elementored',
            constraint=models.UniqueConstraint(fields=('obra', 'codigo'), name='uniq_elemento_codigo_obra'),
        ),
        migrations.AddConstraint(
            model_name='cable',
            constraint=models.UniqueConstraint(fields=('obra', 'codigo'), name='uniq_cable_codigo_obra'),
        ),
        migrations.AddConstraint(
            model_name='cable',
            constraint=models.CheckConstraint(condition=models.Q(('elemento_a', models.F('elemento_b')), _negated=True), name='chk_cable_extremos_distintos'),
        ),
        migrations.AddConstraint(
            model_name='pasotubo',
            constraint=models.UniqueConstraint(fields=('elemento', 'cable', 'tubo'), name='uniq_paso_tubo'),
        ),
        migrations.AddConstraint(
            model_name='fusion',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('puerto_a',), name='uniq_fusion_activa_puerto_a'),
        ),
        migrations.AddConstraint(
            model_name='fusion',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('puerto_b',), name='uniq_fusion_activa_puerto_b'),
        ),
        migrations.AddConstraint(
            model_name='fusion',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True), ('bandeja__isnull', False)), fields=('elemento', 'bandeja', 'posicion'), name='uniq_fusion_activa_bandeja_posicion'),
        ),
        migrations.AddConstraint(
            model_name='fusion',
            constraint=models.CheckConstraint(condition=models.Q(('perdida_db__isnull', True), models.Q(('perdida_db__gte', 0), ('perdida_db__lt', 3)), _connector='OR'), name='chk_fusion_perdida_rango'),
        ),
        migrations.AddConstraint(
            model_name='conexion',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('puerto_a',), name='uniq_conexion_activa_puerto_a'),
        ),
        migrations.AddConstraint(
            model_name='conexion',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('puerto_b',), name='uniq_conexion_activa_puerto_b'),
        ),
        migrations.AddConstraint(
            model_name='puerto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cable__isnull', False), ('fibra__isnull', False), ('tipo', 'FIBRA_CABLE'), ('tubo__isnull', False)), models.Q(('tipo', 'FIBRA_CABLE'), _negated=True), _connector='OR'), name='chk_puerto_fibra_cable_completo'),
        ),
        migrations.AddConstraint(
            model_name='puerto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('puerto__isnull', False), ('splitter__isnull', False), ('tipo__in', ['PUERTO_SPLITTER_IN', 'PUERTO_SPLITTER_OUT'])), models.Q(('tipo__in', ['PUERTO_SPLITTER_IN', 'PUERTO_SPLITTER_OUT']), _negated=True), _connector='OR'), name='chk_puerto_splitter_completo'),
        ),
        migrations.AddConstraint(
            model_name='puerto',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'FIBRA_CABLE')), fields=('elemento', 'cable', 'tubo', 'fibra'), name='uniq_puerto_fibra_cable'),
        ),
        migrations.AddConstraint(
            model_name='puerto',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo__in', ['PUERTO_SPLITTER_IN', 'PUERTO_SPLITTER_OUT'])), fields=('splitter', 'tipo', 'puerto'), name='uniq_puerto_splitter'),
        ),
    ]
