# Generated by Django 5.1.15 on 2026-08-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='umbrales',
            field=models.JSONField(default=dict, help_text='Formato: {"SM": {"ok": x, "warn": y}, "MM": {...}}. Vacío = se copian los del perfil de la operadora al guardar.', verbose_name='umbrales (dB)'),
        ),
    ]
